### ISSUE TITLE
Type issue at block 16803

### ISSUE THREAD

**Issue by ianhe8x** [AcalaNetwork/acala-subql#1]
RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType( │
│ ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 255, in Id, Index, Raw, Address32, Address20

p.s: @polkadot/api version is v3.9.2

**Comment by ianhe8x** [comment]
After I added 
```
Address: AccountId
    LookupSource: AccountId
```
There's another error:
```
Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 15, in Ed25519, Sr25519, Ecdsa
```

**Comment by qwer951123** [comment]
For the acala tc6 network, the app needs a special @polkadot/api version at 3.6.4, can start with "yarn run start"

**Comment by ianhe8x** [comment]
`@subql/node` doesn't use the packages that defined in the query project. It uses the version defined in itself's package.json, and inject the instance into the sandbox context. Also, subql doesn't provide the ability to specify `@polkadot/api` version, it will always use the latest at the moment the docker image is published.
